obj-$(CONFIG_MACH_APQ8064_ARIES) += board-aries.o \
	board-aries-camera.o \
	board-aries-display.o \
	board-aries-gpiomux.o \
	board-aries-gpu.o \
	board-aries-input.o \
	board-aries-misc.o \
	board-aries-pmic.o \
	board-aries-regulator.o \
	board-aries-sound.o \
	board-aries-storage.o

CFLAGS_board-aries-display.o += -Idrivers/video
