GCC_VERSION      := $(shell $(CONFIG_SHELL) $(PWD)/scripts/gcc-version.sh $(CROSS_COMPILE)gcc)
EXTRA_CFLAGS += -Idrivers/media/platform/msm/camera_legacy
EXTRA_CFLAGS += -Idrivers/media/platform/msm/camera_legacy/io
obj-$(CONFIG_MSM_ACTUATOR) += msm_actuator.o
